### ISSUE TITLE
"component is missing a required dependency" after update

### ISSUE THREAD

**Issue by war59312** [zao/foo_wave_seekbar#25]
Hey,

I just updated foo_wave_seekbar from 0.2.34 (2013/04/03) to 0.2.36.1 (2013/05/04).

And Foobar2000 version 1.2.5 to version 1.2.6.

And now I get this on startup of Foobar2000:

Failed to load DLL: foo_wave_seekbar.dll

Reason: This component is missing a required dependency, or was made for different version of foobar2000.

Ouch!

Running on Windows 7 x64 SP1.

Thanks,

Will

**Comment by zao** [comment]
Seems like I just posted about it in the forum thread and forgot to mention it in the changelog...

Since 0.2.35, I now require the [Visual Studio 2012 Update 1 (x86) runtime](http://go.microsoft.com/?linkid=9815734) installed on the target system, or [deployed privately](http://www.acc.umu.se/~zao/public/VisualStudio2012-Update2-x86-runtime.zip) into the foobar2000 directory.

There is sadly no way I can indicate the lack of this runtime in any way, the error you get from foobar2000 is the closest you can get, but I've updated the changelog at least.

Note that the redist you shall install is the x86 one, as it's a 32-bit component.

**Comment by war59312** [comment]
Confirmed, thanks. :D

And indeed I was looking at the change-log at the time. :)
